channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - pip=20.2.4
  - pip:
      - numpy==1.22.0
      - pandas==1.4.4
      - statsmodels==0.13.2
      - prophet==1.1.2
      - azureml-sdk==1.48.0
      - pyyaml==6.0
      - holidays==0.24
      - mltable==1.5.0
      - azureml-mlflow 
      - scikit-learn
      - pathlib
      - argparse
      - nest-asyncio
      #- os
      
# channels:
#   - defaults
#   - anaconda
#   - conda-forge
# dependencies:
#   - python=3.7.5
#   - pip
#   - pip:
#       - azureml-mlflow==1.38.0
#       - azure-ai-ml==1.0.0
#       - pyarrow==10.0.0
#       - scikit-learn==0.24.1
#       - pandas==1.2.1
#       - joblib==1.0.0
#       - matplotlib==3.3.3
#       - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
#       - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector
